name: BEAST_ENV
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - flake8
  - black
  - pytorch
  - torchvision
  - torchaudio
  - tqdm
  - pyyaml
  - matplotlib-inline
  - statsmodels
  - plotly
  - nbformat
