name: IBUN_BEAST
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - flake8
  - black
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - tqdm
  - pyyaml
  - matplotlib-inline
  - statsmodels
  - plotly
  - nbformat
  - pygad
  - wandb
  - u8darts-all
