name: IBUN_BEAST
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - flake8
  - black
  - tqdm
  - pyyaml
  - matplotlib-inline
  - statsmodels
  - plotly
  - nbformat
  - pygad
  - wandb
  - pip
  - pip:
      - "u8darts[all]"
  # GPU-enabled PyTorch stack
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
